services:
  app:
    container_name: web-server-container
    hostname: web-server
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ../:/app:cached
      - react_node_modules:/app/node_modules
    tty: true
    networks:
      - scheduler

networks:
  scheduler:
    external: true

volumes:
  react_node_modules: