FROM node:latest
WORKDIR /app

RUN apt update \
    && apt-get -y install sudo \
    && sudo echo node:node | chpasswd \
    && sudo echo 'node ALL=(ALL) ALL' >> /etc/sudoers

ENV TZ Asia/Tokyo
ENV TERM xterm
ENV PYTHONPATH $PYTHONPATH:/app/src
ENV PATH $PATH:/home/vscode/.local/bin
ENV APP_SERVER http://app-server:5000

RUN mkdir -p node_modules \
    && chown node node_modules